name: Publish on version change

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: 18.x
    - name: Get current version
      id: get_version
      run: echo "::set-env name=VERSION::$(node -p 'require(`./package.json`).version')"
    - name: Check version and publish
      if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Bump version')
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        if [ "${{ env.VERSION }}" != "$(node -p "require('./package.json').version")" ]; then
          npm publish
        else
          echo "Version has not changed. Skipping publish."
        fi